import { StyleSheet, Dimensions } from "react-native";

// Get device dimensions
const { width, height } = Dimensions.get("window");

// Colores y tema
export const COLORS = {
  primary: "#07bbfd",
  secondary: "#88d42b",
  white: "#ffffff",
  black: "#000000",
  lightGray: "#f8f9fa",
  darkGray: "#333333",
  success: "#4caf50",
  error: "#f44336",
  warning: "#ff9800",
  shadow: "rgba(0,0,0,0.1)",
  overlay: "rgba(0,0,0,0.6)",
};

// Gradientes
export const GRADIENT_COLORS = ["#e6f7ff", "#ccf0ff", "#b3e0ff"];
export const CARD_GRADIENT = ["#ffffff", "#f8f9fa"];
export const HEADER_GRADIENT = [COLORS.primary, "#0599d4"];
export const MAIN_CARD_GRADIENT = ["#ffffff", "#f8f9fa"];

export const styles = StyleSheet.create({
  gradientBackground: {
    flex: 1,
  },
  containerCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.white,
  },
  loadingText: {
    marginTop: 10,
    color: COLORS.darkGray,
    fontSize: 14,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: COLORS.black,
  },
  headerSubtitle: {
    fontSize: 14,
    color: COLORS.black,
    opacity: 0.9,
  },
  spinning: {
    opacity: 0.7,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
  },
  mainCardContainer: {
    flex: 1,
    marginTop: 10,
    marginBottom: 15,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: COLORS.black,
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
  },
  mainCard: {
    flex: 1,
    borderRadius: 20,
    overflow: "hidden",
  },
  mainCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  mainCardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.darkGray,
    marginLeft: 10,
  },
  searchSection: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginHorizontal: 15,
    marginTop: 10,
    marginBottom: 8,
    alignItems: "center",
  },
  searchPlaceholder: {
    flex: 1,
    marginLeft: 10,
    color: "#9e9e9e",
    fontSize: 14,
  },
  adminBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: `${COLORS.warning}15`,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: `${COLORS.warning}30`,
  },
  adminBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.warning,
    marginLeft: 4,
  },
  scrollContainer: {
    paddingHorizontal: 15,
    paddingBottom: 20,
    paddingTop: 8,
  },
  card: {
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: COLORS.black,
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
    overflow: "hidden",
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  cardContent: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
  },
  cardImageContainer: {
    width: 70,
    height: 70,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: COLORS.lightGray,
    justifyContent: "center",
    alignItems: "center",
  },
  cardImage: {
    width: 60,
    height: 60,
    resizeMode: "contain",
  },
  cardInfo: {
    flex: 1,
    paddingLeft: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.darkGray,
    marginBottom: 2,
  },
  cardDescription: {
    fontSize: 13,
    color: "#777",
    marginBottom: 8,
  },
  statsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  progressContainer: {
    flex: 1,
  },
  progressBar: {
    height: 6,
    backgroundColor: "#eee",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    color: "#777",
    marginTop: 4,
  },
  arrowContainer: {
    marginLeft: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: `${COLORS.primary}10`,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: "500",
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.overlay,
  },
  modalContainer: {
  backgroundColor: COLORS.white,
  width: "92%",
  maxHeight: height * 0.88, 
  borderRadius: 16,
  overflow: "hidden",
  shadowColor: COLORS.black,
  shadowOpacity: 0.3,
  shadowRadius: 10,
  shadowOffset: { width: 0, height: 5 },
  elevation: 5,
  paddingBottom: 10, 
},
  modalHeader: {
    padding: 16,
    paddingTop: 20,
  },
  modalHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  modalTitle: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 10,
    flex: 1,
  },
  adminModalBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    right: 12,
    top: 15,
    zIndex: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalImageContainer: {
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  modalImage: {
    width: 95,
    height: 95,
    resizeMode: "contain",
  },
  modalDescription: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginTop: 8,
    paddingHorizontal: 20,
  },
  modalDivider: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#eee",
  },
  dividerText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginHorizontal: 10,
  },
  modalContent: {
    padding: 15,
  },
  codigoItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.08)",
    shadowColor: COLORS.black,
    shadowOpacity: 0.03,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  codigoIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.8)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  codigoTexto: {
    flex: 1,
    fontSize: 15,
    fontWeight: "500",
    color: "#333",
  },
  codigoActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  editIcon: {
    marginLeft: 8,
    opacity: 0.6,
  },
  codigoTextContainer: {
    flex: 1,
    marginRight: 10,
  },
  switchContainer: {
    alignItems: "center",
    justifyContent: "center",
    minWidth: 60,
  },
  switch: {
    transform: [{ scaleX: 1.1 }, { scaleY: 1.1 }],
  },
  modalFooter: {
    padding: 15,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    alignItems: "center",
    paddingBottom: 25,
  },
  adminInstructions: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginBottom: 10,
    fontStyle: "italic",
  },
  primaryButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 10,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  primaryButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    fontSize: 16,
  },
});
